### ISSUE TITLE
focal problem in training.

### ISSUE THREAD

**Issue by zzzyy1997** [jiwei0921/MoLF#2]
thank for your work!
when i use your code,i got a problem, focal size is not 256*256*36 ,but sometimes  is 230*230*36.
`
(230, 230, 36)
(256, 256, 36)
(230, 230, 36)
(256, 256, 36)
(230, 230, 36)
(256, 256, 36)
(230, 230, 36)
(230, 230, 36)
(256, 256, 36)
Traceback (most recent call last):
  File "/home/zy/PycharmProjects/MF_code/demo2.py", line 133, in <module>
    training.train()
  File "/home/zy/PycharmProjects/MF_code/trainer2.py", line 207, in train
    self.train_epoch()
  File "/home/zy/PycharmProjects/MF_code/trainer2.py", line 95, in train_epoch
    f1,f2,f3,f4,f5 = self.model_focal(focal)  # FocalNet's output
  File "/home/zy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zy/PycharmProjects/MF_code/model.py", line 384, in forward
    pool5 = pool5 + pool4 + pool3
RuntimeError: The size of tensor a (60) must match the size of tensor b (58) at non-singleton dimension 3

`

**Comment by jiwei0921** [comment]
Sorry for my late. You can try add a resize function. This problem is due to the image augmentation flipping.

**Comment by zzzyy1997** [comment]
Dear sir
     Thanks for your reply，I have already added a resize function and the problem  above has solved.
